language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true udemy-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "udemy-docker-react"
  env: "UdemyDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-346801759259"
  bucket_path: udemy-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
